import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, SignInButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.example.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>{!user.isSignedIn && <SignInButton />}</div>

        <div>
          <h1>Muscles</h1>
          {data?.map(muscle => (<div key={muscle.id}>{muscle.name}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
